Section "Module"
    Load "fbdev"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "fbdev"
EndSection

Section "Module"
    Load "evdev"
EndSection

Section "InputDevice"
    Identifier "PS2Keyboard"
    Driver "evdev"
    Option "Device" "/dev/input/event1"
    Option "CoreKeyboard"
EndSection

Section "InputDevice"
    Identifier "PS2Mouse"
    Driver "evdev"
    Option "Device" "/dev/input/event2"
    Option "CorePointer"
EndSection
